quarkus :
  datasource :
    db-kind : mysql
    username : root
    password : root
    jdbc:
      url : jdbc:mysql://localhost:3306/my_db_movie
  hibernate-orm :
    database :
      generation : update
  http :
    port : 8080
  log :
    console :
      level : INFO

"%dev" :
  quarkus :
    http :
      port : 8081
    log :
      console:
        level : ALL

"%test" :
  quarkus :
    datasource :
      db-kind : h2
      jdbc:
        url : jdbc:h2:mem:db
    hibernate-orm :
      dialect : org.hibernate.dialect.H2Dialect
      sql-load-script : META-INF/sql/import-test.sql
      database :
        generation : drop-and-create
    http :
      port : 9090
      access-log :
        enabled : true
    log :
      console :
        level : DEBUG

  "%prod" :
    quarkus :
      package :
        type : uber-jar
